INSERT INTO MPA (NAME)
SELECT 'G' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME = 'G');

INSERT INTO MPA (NAME)
SELECT 'PG' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME = 'PG');

INSERT INTO MPA (NAME)
SELECT 'PG-13' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME = 'PG-13');

INSERT INTO MPA (NAME)
SELECT 'R' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME = 'R');

INSERT INTO MPA (NAME)
SELECT 'NC-17' WHERE NOT EXISTS (SELECT * FROM MPA WHERE NAME = 'NC-17');

INSERT INTO GENRES (NAME)
SELECT 'Комедия' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Комедия');

INSERT INTO GENRES (NAME)
SELECT 'Драма' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Драма');

INSERT INTO GENRES (NAME)
SELECT 'Мультфильм' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Мультфильм');

INSERT INTO GENRES (NAME)
SELECT 'Триллер' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Триллер');

INSERT INTO GENRES (NAME)
SELECT 'Документальный' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Документальный');

INSERT INTO GENRES (NAME)
SELECT 'Боевик' WHERE NOT EXISTS (SELECT 1 FROM GENRES WHERE NAME = 'Боевик');
